version: "3.7"
services:
  load_tester:
    image: josh/load-tester
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
networks:
  default:
    external:
      name: tbg_development
